import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createMetricHudFrame } from '../src/lib/media/metricHudFrame';
import { metricHudFrameFixtures } from '../src/lib/media/metricHudFrame.fixtures';
import { metricHudFrameSvgDocument } from '../src/lib/media/metricHudSvg';

type ResvgConstructor = new (
	svg: string,
	options?: unknown
) => { render: () => { asPng: () => Uint8Array } };

const outputDir = join(process.cwd(), 'docs/video/fixtures/burned-hud-parity');

function slug(value: string): string {
	return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function escapeHtml(value: string): string {
	return value
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}

async function main(): Promise<void> {
	await mkdir(outputDir, { recursive: true });
	const { Resvg } = (await import('../functions/node_modules/@resvg/resvg-js/index.js')) as {
		Resvg: ResvgConstructor;
	};

	const sections: string[] = [];
	for (const fixture of metricHudFrameFixtures) {
		const frame = createMetricHudFrame(fixture);
		const svg = metricHudFrameSvgDocument(frame);
		const name = slug(fixture.name);
		const svgFile = `${name}.svg`;
		const pngFile = `${name}.png`;
		await writeFile(join(outputDir, svgFile), svg);
		const png = new Resvg(svg, {
			fitTo: { mode: 'original' },
			font: {
				loadSystemFonts: true,
				defaultFontFamily: 'DejaVu Sans'
			}
		}).render().asPng();
		await writeFile(join(outputDir, pngFile), png);
		sections.push(`<section>
<h2>${escapeHtml(fixture.name)}</h2>
<div class="pair">
<figure><figcaption>Shared SVG</figcaption><img src="${svgFile}" alt="${escapeHtml(fixture.name)} shared SVG fixture"></figure>
<figure><figcaption>Server raster PNG</figcaption><img src="${pngFile}" alt="${escapeHtml(fixture.name)} rasterized PNG fixture"></figure>
</div>
</section>`);
	}

	await writeFile(
		join(outputDir, 'index.html'),
		`<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Burned HUD Parity Fixtures</title>
<style>
body { margin: 0; padding: 24px; background: #020617; color: #e2e8f0; font-family: system-ui, sans-serif; }
h1 { margin: 0 0 8px; font-size: 24px; }
p { margin: 0 0 24px; color: #94a3b8; }
section { margin: 0 0 28px; }
h2 { margin: 0 0 12px; font-size: 16px; color: #cbd5e1; }
.pair { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; align-items: start; }
figure { margin: 0; padding: 12px; border: 1px solid rgba(148, 163, 184, 0.22); border-radius: 8px; background: #000; }
figcaption { margin: 0 0 8px; color: #94a3b8; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; }
img { display: block; width: 100%; height: auto; }
</style>
<h1>Burned HUD Parity Fixtures</h1>
<p>Generated by <code>npx tsx scripts/generate-hud-parity-fixtures.ts</code>.</p>
${sections.join('\n')}
</html>
`
	);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});